### ISSUE TITLE
kth数据集问题

### ISSUE THREAD

**Issue by JCChen778** [chengtan9907/OpenSTL#28]
你好！首先，非常感谢你提供的优秀的代码库。

这两天我在尝试运行你的代码，遇到了一些问题：

1. scikit-image的版本应该小于0.19，否则在test时计算ssim会出现有关win-size的报错

2.可视化文档（docs/en/visualization/video_visualization.md）中的指令 
python tools/visualizations/vis_video.py -d mmnist -w work_dirs/EXP/ --index 0 --save_dirs fig_mmnist_vis可能有误
我尝试模仿这个指令的格式进行输入，发生报错
Traceback (most recent call last):
  File "tools/visualizations/vis_video.py", line 136, in <module>
    main()
  File "tools/visualizations/vis_video.py", line 50, in main
    base_dir = base_dir.split(method_list[0])[0]
ValueError: empty separator
当我把指令中’work_dirs/EXP/‘最后的/去掉后可视化能正常运行
所以我认为正确的指令格式应该是
python tools/visualizations/vis_video.py -d mmnist -w work_dirs/EXP --index 0 --save_dirs fig_mmnist_vis

3.我尝试使用文档中的方法加载kth数据集（数据为视频形式）
bash tools/prepare_data/download_kth.sh
python tools/train.py -d kth --lr 1e-3 -c configs/kth/PredRNNv2.py --ex_name kth-prev2
报错
NotADirectoryError: [Errno 20] Not a directory: './data/kth/boxing/person13_boxing_d4_uncomp.avi'
然后我去下载了原prernn库中提供的kth数据集（数据为图片形式）
python tools/train.py -d kth --lr 1e-3 -c configs/kth/PredRNNv2.py --ex_name kth-prev2
数据能加载一部分，但很快就out of memory了
我使用的是24G的3090进行训练，在原prernn库中训练时并不会遇到这个问题

最后，如果可以的话能在百度网盘中提供一下你使用的kth数据集吗？非常感谢

**Comment by Lupin1998** [comment]
Hi @JCChen778, thanks very much for your detailed suggestions! We have fixed bug 1 and bug 2 you mentioned in the latest commit. As for the out-of-memory issue, I measure the peak GPU memory of PredRNN on V100 (32G) with OpenSTL, which is 26G (training) and 10G (testing). The different GPU memory between OpenSTL and the official implementation in  [PredRNN](https://github.com/thuml/predrnn-pytorch) is the batch size (16 vs. 4). Moreover, we have uploaded the KTH dataset (i.e., `kth_action.zip` provided in [PredRNN](https://github.com/thuml/predrnn-pytorch)) in [Baidu Cloud](https://pan.baidu.com/s/1fudsBHyrf3nbt-7d42YWWg?pwd=kjfk).

**Comment by tjnkyqcy** [comment]
您好，非常感谢您再STL模型方面做出的贡献，给我提供了很多帮助。
我想请教一下，从问题“kth数据集问题  #28”@JCChen778中发现了和我遇到类似的问题，但是我依然没有解决，希望得到您的指导。
我的问题：在进行可视化的时候遇到提示错误：
E:\Anaconda3\envs\pytorch-gpu-openSTL\python.exe H:/OpenSTL-master/tools/visualizations/vis_video.py -d mmnist -w work_dirs/Debug --index 0 --save_dirs fig_mmnist_vis
Traceback (most recent call last):
  File "H:/OpenSTL-master/tools/visualizations/vis_video.py", line 136, in <module>
    main()
  File "H:/OpenSTL-master/tools/visualizations/vis_video.py", line 45, in main
    assert os.path.isdir(args.work_dirs)
AssertionError

Process finished with exit code 1
开始怀疑可能是work_dir的路径不正确，按照可视化文档（docs/en/visualization/video_visualization.md）中的指令进行修改后，
-d mmnist -w work_dirs/Debug --index 0 --save_dirs fig_mmnist_vis
仍然不能解决，以下是我从官网下载程序包并训练之后得到的文件的相关结构，是否与您的相同。谢谢。

OpenSTL-master
   |--tools
   |    |--visualizations
   |    |    |--vis_video.py
   |    |--work_dirs
   |    |    |--Debug 
   |    |    |    |--checkpoints
   |    |    |    |    |--lastest.pth
