### ISSUE TITLE
分布式训练

### ISSUE THREAD

**Issue by rs-lsl** [chengtan9907/OpenSTL#61]
你好，我在尝试分布式训练时，遇到了如下bug，其中--local_rank '0, 1' --dist True --launcher 'pytorch'这几个参数是这样设置的，

Traceback (most recent call last):
  File "OpenSTL_master/tools/train.py", line 57, in <module>
    exp = BaseExperiment(args)
  File "/home/lisl/OpenSTL_master/openstl/api/train.py", line 50, in __init__
    self._preparation(dataloaders)
  File "/home/lisl/OpenSTL_master/openstl/api/train.py", line 88, in _preparation
    init_dist(self.args.launcher, **dist_params)
  File "/home/lisl/OpenSTL_master/openstl/utils/main_utils.py", line 246, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/home/lisl/OpenSTL_master/openstl/utils/main_utils.py", line 286, in _init_dist_pytorch
    rank = int(os.environ['RANK'])
  File "/home/lisl/.conda/envs/pytorch0/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'

请问这个bug是为什么，是不是哪个参数没有设置？

**Comment by Lupin1998** [comment]
Hi, thanks for your question. We recommend use `tools/dist_train.sh` according to [get_started.md](https://github.com/chengtan9907/OpenSTL/blob/master/docs/en/get_started.md) rather than setup distributed training with `tools/train.py`.

**Comment by rs-lsl** [comment]
Thank you!

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
