### ISSUE TITLE
Question about the MIM algorithm in OPEN-STL

### ISSUE THREAD

**Issue by tjnkyqcy** [chengtan9907/OpenSTL#79]
rain loss: 0.2278 | data time: 0.1920: 100%|██████████| 57/57 [01:02<00:00,  1.10s/it]
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> ] 32/33, 1.3 task/s, elapsed: 24s, ETA:     1sTraceback (most recent call last):
  File "H:/OpenSTL-master/tools/train.py", line 42, in <module>
    exp.train()
  File "H:\OpenSTL-master\openstl\api\train.py", line 332, in train
    vali_loss = self.vali()
  File "H:\OpenSTL-master\openstl\api\train.py", line 354, in vali
    results, eval_log = self.method.vali_one_epoch(self, self.vali_loader)
  File "H:\OpenSTL-master\openstl\methods\base_method.py", line 205, in vali_one_epoch
    results = self._nondist_forward_collect(vali_loader, len(vali_loader.dataset), gather_data=False)
  File "H:\OpenSTL-master\openstl\methods\base_method.py", line 166, in _nondist_forward_collect
    pred_y = self._predict(batch_x, batch_y)
  File "H:\OpenSTL-master\openstl\methods\predrnn.py", line 56, in _predict
    img_gen, _ = self.model(test_dat, real_input_flag, return_loss=False)
  File "E:\Anaconda3\envs\pytorch-gpu-openSTL\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\OpenSTL-master\openstl\models\mim_model.py", line 105, in forward
    h_t[i], c_t[i], st_memory = self.stlstm_layer[i](
  File "E:\Anaconda3\envs\pytorch-gpu-openSTL\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\OpenSTL-master\openstl\modules\mim_modules.py", line 133, in forward
    cell = torch.cat((new_c, new_m), 1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 2 but got size 1 for tensor number 1 in the list.

Applying the MIM algorithm causes this problem at the end of training, resulting in a non-functioning？

**Comment by chengtan9907** [comment]
This algorithm requires `args.batch_size == args.val_batch_size`, did you change the val_batch_size?

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
